markdown:    kramdown
future:      true
baseurl:     ''
encoding:    UTF-8
timezone:    America/Sao_Paulo

title:       "Portifolio Personal"
description: "Personal website of developer and webdesigner Charles Cabral."
teaser:      default-teaser.png
logo:        site-logo.png
color:       '#2C2C2C'
locale:      pt

include:
  - _pages

exclude:
  - README.md
  - vendor/bundle/ruby
  - package.json
  - node_modules
  - gulpfile.js
  - bower.json
  - Gemfile
  - CNAME
  - Gemfile.lock
  - .npmignore

compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false