markdown: kramdown
baseurl: /charlescabral.in
include: ['_pages', '_projects']
exclude: ['README.md','vendor/bundle/ruby']
permalink: /:title/
collections:
  projects:
    output: true
    permalink: /work/:path/